name: lekhok_app
description: Lekhok Webview App
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0 # সংস্করণটি পরিবর্তন করে ৪.৮.০ করা হলো

flutter:
  uses-material-design: true
